name: Update Repo

on:
    push:
        branches:
          - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install lz4
              run: sudo apt -y install lz4

            - name: Import GPG Key
              uses: crazy-max/ghaction-import-gpg@v4
              with:
                gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                passphrase: ${{ secrets.GPG_PASSPHRASE }}

            - name: Build repository
              run: |
                bash build.sh

            - name: Create ghpages artifact
              uses: actions/upload-pages-artifact
              with:
                path: "publish/"

    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
          
